[[Leptonica]]
arch = "i686"
git-tree-sha1 = "cbd59684f87b9f2f6e5b8949e923147cf6178fd4"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "775c0c8a7fe087ac490d12c8598195c057abcd795e2ccf9245304c679d022aa2"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.i686-linux-musl.tar.gz"
[[Leptonica]]
arch = "aarch64"
git-tree-sha1 = "6a5fc8328f3697a275370298a0d6bf70f627e6ae"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "25d078d6ef99112b66305f38464853237a40b556c11f7e65e719e3b7ba5cfda0"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.aarch64-linux-musl.tar.gz"
[[Leptonica]]
arch = "i686"
git-tree-sha1 = "88a133900489a33c97124a6492327e86225850b0"
os = "windows"

    [[Leptonica.download]]
    sha256 = "00cc13953a43c36fad608766bf471f316e1ab0f99db142b8e110f63d16d29675"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.i686-w64-mingw32.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "0ac0f566cd8b842a9d156dc7cd569a1d206a29a7"
os = "windows"

    [[Leptonica.download]]
    sha256 = "e5b8ac0110d0df30d8a15f669206fddcf8af866dc23fb2c33e373ea7ce1ab323"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.x86_64-w64-mingw32.tar.gz"
[[Leptonica]]
arch = "armv7l"
git-tree-sha1 = "d3f7f72bb3ec6dbd03a3e938f6ef8ae64bf7e743"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "4d72f3590e5ab441a660ed8e6993858690934a565c42070b9206125b5bc79cf9"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.armv7l-linux-gnueabihf.tar.gz"
[[Leptonica]]
arch = "armv7l"
git-tree-sha1 = "e919b0f15c1341cab1e9aae03feb39f649702395"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "8137832631655620da80dc2f743ae8b69693e82dcbbf2084a90e90976475a013"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.armv7l-linux-musleabihf.tar.gz"
[[Leptonica]]
arch = "i686"
git-tree-sha1 = "43f49117a2e860ceeca9a1d17dd149f0451a5f68"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "1af84ce7e405838d5496f499b3e50671c09f9a5369bdf0efac84abdb95d40bd0"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.i686-linux-gnu.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "d0f86a612e2be3570b57846915c4120ca8040d4d"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "64771959b1749e74a49c35e6fbfd98726a5bafa648b9638862b0054abdd2022f"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.x86_64-linux-gnu.tar.gz"
[[Leptonica]]
arch = "powerpc64le"
git-tree-sha1 = "606d77844f0fecd3be84f1724d8470df89256173"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "888059467176d8af1f0afc63583f36e59f9d1f890ada18c8b6b3005224544269"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.powerpc64le-linux-gnu.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "76b11cac43b5d3abc08c409eedde3a67d118417a"
os = "macos"

    [[Leptonica.download]]
    sha256 = "c99702f394cf71a35de02c49d198a6994c1b5200471a949bb639ceb5c8efa156"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.x86_64-apple-darwin14.tar.gz"
[[Leptonica]]
arch = "aarch64"
git-tree-sha1 = "e599179ee7fbda7cf92cfdf45c63bdc1ac10b33c"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "2e5401bb4ff6138e95c16032eb8234382bb00d04376390c7b9a039d5f933d6bb"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.aarch64-linux-gnu.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "cf2acfeb9f2f19d3155d3f711478b1d7720993ea"
os = "freebsd"

    [[Leptonica.download]]
    sha256 = "d084fe7ef3fb28a1708f160eda1a7e7a38f92a8ada5550b8c90ccf5d4991bfb0"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "5ae099d1bc7628d43c6b0bfac832c87a30db081b"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "a4604a12b6bc23d77cd21dd616852950e4f2560fb9ddaba87e13bb3c4bc657ab"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+0/Leptonica.v1.79.0.x86_64-linux-musl.tar.gz"
