[[Leptonica]]
arch = "i686"
git-tree-sha1 = "fe790dd0b126dda55767ded87242bd6f903206f0"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "d19dd03a6c33771e016d643cd295c1d6795b3c1a699f2e06b98f99a00c675476"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.i686-linux-gnu.tar.gz"
[[Leptonica]]
arch = "i686"
git-tree-sha1 = "e797693e1d53eaf93274ec184c9639ceb73f396d"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "32c1cb4709248e3fcd3f4d0ccf4d8c8b6a93c6e09fbc51893adbd3a822bb335d"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.i686-linux-musl.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "5c40a0fc7e997279f8d517d06c6dfc86609482d4"
os = "macos"

    [[Leptonica.download]]
    sha256 = "f304e998099a99eb0ff556effd86ccacbafed527ae76ba9bab58c7104640dab4"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.x86_64-apple-darwin14.tar.gz"
[[Leptonica]]
arch = "powerpc64le"
git-tree-sha1 = "cf3fc108df131db1c4c355a5cc6a0ed44b089b6d"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "10356f5cff1e020be4997ed228bd73ece66aac89e7038b590513b7c14098f140"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.powerpc64le-linux-gnu.tar.gz"
[[Leptonica]]
arch = "aarch64"
git-tree-sha1 = "1c3a7017a2ca988338b445ef89a7d63a69f8a407"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "e44a031ad9fa51316eba45606da0473b732c4c00a3dfe35651f0d522743fcdb4"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.aarch64-linux-gnu.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "85fa1315ee7bba789c45ce043d857da772e0791c"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "ae830cb7750e5083caf19e5ddf98b4dbb75641c6b9640b7f061f439306ddea99"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.x86_64-linux-musl.tar.gz"
[[Leptonica]]
arch = "aarch64"
git-tree-sha1 = "1a196ab433d7751a38083c0a9a5cc06381061da1"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "232a6657641982433c64e211ab87486daee62fbab172a064279227d40e095a58"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.aarch64-linux-musl.tar.gz"
[[Leptonica]]
arch = "armv7l"
git-tree-sha1 = "3ce2d13da137ce56f25bde662002f75581f2f987"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "e412e3c542f4a939789439b7a24b62af2e45eebd00500f7d56fce9d94e5264f5"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.arm-linux-musleabihf.tar.gz"
[[Leptonica]]
arch = "i686"
git-tree-sha1 = "2ba85f89569105c294fbf6152b3267a61809b619"
os = "windows"

    [[Leptonica.download]]
    sha256 = "1082184d1e24d61d447b9560cc477f36e503f2476513f97074a3141ac40ff4f3"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.i686-w64-mingw32.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "176d2ccd7bd02b05d587427b65fd1882d3678fe4"
os = "freebsd"

    [[Leptonica.download]]
    sha256 = "b25dbef304750ac9659ceeb640102f7c2f52a39b37f22c09886439b3ea499b77"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Leptonica]]
arch = "armv7l"
git-tree-sha1 = "d69ba628e5a5979c73fe96c9bb72f514d738f816"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "fef030de222d383aee05baf886c4ec0d33d5f4ef87d3abaaa25c86cee8ff9a63"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.arm-linux-gnueabihf.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "92319988d70e6e0390c934e1dcbea8461212752b"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "ce6f9d863c594ccfe4b37d0756cf1776315ccd5a7ff3e0768aaeb1bc3060af9a"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.x86_64-linux-gnu.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "d6da8f5a740476440a67c3ce8bb019ec5c81144e"
os = "windows"

    [[Leptonica.download]]
    sha256 = "f96784db959b314e175424f6fd4c89dc13c077a5655b755ca7f14f2a663ce8a6"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.78.0+1/Leptonica.v1.78.0.x86_64-w64-mingw32.tar.gz"
