[[Leptonica]]
arch = "aarch64"
git-tree-sha1 = "e60a9f9b26cec4dff9ff0130157661147fe68312"
os = "macos"

    [[Leptonica.download]]
    sha256 = "561d7ed6054c26b08c7bc8ee5d125fc1d97ac54ee79fea4b61d1c0403e29fc4c"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.aarch64-apple-darwin.tar.gz"
[[Leptonica]]
arch = "aarch64"
git-tree-sha1 = "a01d83a6b588a13a9e3405d6b330f7dbbb029915"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "afc88c5e3633b39fa2f49def892d0bad72a6b57dd4f704f74b3184b9b9323d42"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.aarch64-linux-gnu.tar.gz"
[[Leptonica]]
arch = "aarch64"
git-tree-sha1 = "ea3b5bc243efea9105305d3f0a018afc27638530"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "7d4ade1a7d1a607a5cbc3944b983fbae546c14e3ab7402b337a3ba01161a4bee"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.aarch64-linux-musl.tar.gz"
[[Leptonica]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5bd58ef10cf3a6f61d10ac3f64c3fdf3c266ac48"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "15cebf3612a9ce90e4cec7ecf586045f33bee22a31d825c8055462513ce64559"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.armv6l-linux-gnueabihf.tar.gz"
[[Leptonica]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "29f63c32e300a0735221b257b4e713fb7ac1e3d6"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "aa718c383778539b05a200648134d5ba10f9bf0061525599cfe5fa3d0c7067d1"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.armv6l-linux-musleabihf.tar.gz"
[[Leptonica]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d52a71ebc80c9c98f7a8fffe692fcf419c3e568"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "5add9b515f47287d41d57b468e0d415fea0937bd647a057d7d8daca7c29f6594"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.armv7l-linux-gnueabihf.tar.gz"
[[Leptonica]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c43b1f8e6df75520bd9549536c857fe2ec2ad27"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "feb0dbbcdf7db6e08f342144621d1c4ab5abb637781878545e7091f1d6330904"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.armv7l-linux-musleabihf.tar.gz"
[[Leptonica]]
arch = "i686"
git-tree-sha1 = "ba434fe21b4afb2079d265a697883740250aef9b"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "c3129ee00793e013232aa61549bcf23c8afde7ac352bed304e8664df1a1d26be"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.i686-linux-gnu.tar.gz"
[[Leptonica]]
arch = "i686"
git-tree-sha1 = "1a6942da66af68a16519274e5ecde85c7f36b44c"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "39070ec7c3bff72c68af323b6fdfb133b168342650c27d636d32c794baf9108d"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.i686-linux-musl.tar.gz"
[[Leptonica]]
arch = "i686"
git-tree-sha1 = "2861eaa9d0ec476b5e23f5eaa6f0d29a4e3abc9b"
os = "windows"

    [[Leptonica.download]]
    sha256 = "40b835838925257b92451fd31c91576ae95d15985ba8bb2281594c75fd9b8b0c"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.i686-w64-mingw32.tar.gz"
[[Leptonica]]
arch = "powerpc64le"
git-tree-sha1 = "851fc1a638faed1e7cfc6d35fae3b785d2e5ea1e"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "2dfd8036ae8a3856777a44096ef148bb8f56992469e16774849f9c9f99643fc8"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.powerpc64le-linux-gnu.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "6e7309cb79a4925aa1d2cdd08067b422797859ed"
os = "macos"

    [[Leptonica.download]]
    sha256 = "99d4207bd944da3697a8e5552b133891f9101d289f800b2b9a51d39acb175e62"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.x86_64-apple-darwin.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "aef82a96ac263059d12e98dda6dd1d1f6bd28418"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "2940f932e6ff263755ba55cfa748f854b6e878a52b7c4c893d128ec00d7cd14a"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.x86_64-linux-gnu.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "d4cef62a61e786d5fb914fc2b569f6aa29808172"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "d7d3a92ce448ea3da559b0a502c13fc270fd840d8169dd03bbc8ec778fc63f02"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.x86_64-linux-musl.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "6d7c82e06e2dab833463c79eb0287a34332c4ff0"
os = "freebsd"

    [[Leptonica.download]]
    sha256 = "4dce87ee8918cf15dbf9c005d8a8f2b1122d366e315a42ded795480782346aa4"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.x86_64-unknown-freebsd.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "be01b59588226d3248a7ea568fe2233f38fce894"
os = "windows"

    [[Leptonica.download]]
    sha256 = "470b18bd3321af0f167449c0e68e2a3ec189f3af51ea00263e9862b5ae1dfefc"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.82.0+0/Leptonica.v1.82.0.x86_64-w64-mingw32.tar.gz"
