[[Leptonica]]
arch = "i686"
git-tree-sha1 = "c41ef1b67179b1a5c328094fec10bd995c1337df"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "6ef9e537f5ecc491090a33f6c2f7b61af380c8a1e7d6d43a5c1ab0546f5cb44e"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.i686-linux-musl.tar.gz"
[[Leptonica]]
arch = "aarch64"
git-tree-sha1 = "e8bcdd057060282bbe74edeb34402d5c13988231"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "faeb8816b4396742e614b213b7eaefb094cb6667f676ecdc9588d18c58fb7f76"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.aarch64-linux-musl.tar.gz"
[[Leptonica]]
arch = "i686"
git-tree-sha1 = "9e9a5e2c184a1504ed5ef7d94357a7937b682c52"
os = "windows"

    [[Leptonica.download]]
    sha256 = "59d897334a5daeb8d17ccb05e0ead6f3eb4f949464999c718c6c62065d1e70fb"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.i686-w64-mingw32.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "c61b93990091252de9dba6aca2c2ed812a68283b"
os = "windows"

    [[Leptonica.download]]
    sha256 = "bd9f47bffa5fee7ce81bde57afb778aaf30a6a59464c1f20eec12459f9bb48dd"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.x86_64-w64-mingw32.tar.gz"
[[Leptonica]]
arch = "armv7l"
git-tree-sha1 = "ae866005cc7f6204a6c619b29a7bbb3a767f0383"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "d1152b85d4bfa9fb60648a9b51066e5f1089b6cc902308ee190385d8639f6cbf"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.armv7l-linux-gnueabihf.tar.gz"
[[Leptonica]]
arch = "armv7l"
git-tree-sha1 = "d72650c2c176c487908d7b88c8fe0d6a6793371b"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "17c6678db5c1b567e63207b7d11fca5a181b20014cffd4604890dbbe748f56e6"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.armv7l-linux-musleabihf.tar.gz"
[[Leptonica]]
arch = "i686"
git-tree-sha1 = "698118ad750a61b1020d58777f0d431ee34c5da8"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "81d20a9aeb88072b61bfb4e328ab086ff7b160788221b1879adfb821c9f2ae54"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.i686-linux-gnu.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "568c691dc012e9187f9956e4f352f0ae3b1abef4"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "d9d44bde04403afecc7d3373ad76cc8f2e577f6813043913f8e2a9a362fbe138"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.x86_64-linux-gnu.tar.gz"
[[Leptonica]]
arch = "powerpc64le"
git-tree-sha1 = "222d006f5e17eb4406cc94495a5b3d8b773dc70b"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "6235612ab43ec7101f6db446b962c83822163c0bf4c85e4e38083a803363d7c8"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.powerpc64le-linux-gnu.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "3e0fd6b8cc8d120ed2ef0758b3d8ff8c9719a7d9"
os = "macos"

    [[Leptonica.download]]
    sha256 = "3a3d4be82a16623ed6c27202a1e55fdafd0e6dfc2c88a539531e3aef4b548691"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.x86_64-apple-darwin14.tar.gz"
[[Leptonica]]
arch = "aarch64"
git-tree-sha1 = "f7866256fb9de2b178f75924554d72af0a9df779"
libc = "glibc"
os = "linux"

    [[Leptonica.download]]
    sha256 = "07a9cdd4f216405303a7c260c0941aa7944a8960a9a06aa1fe21ff1f38da010b"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.aarch64-linux-gnu.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "640ded50d971e5ba58ee0349d516d125453ae954"
os = "freebsd"

    [[Leptonica.download]]
    sha256 = "ed92c2d0ee994972a8931241091138dfaf70654a3bde83108b3e6dfcf54061e9"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Leptonica]]
arch = "x86_64"
git-tree-sha1 = "8ed4df5cfac4d4fe9b653ece09f0161cb2daffd9"
libc = "musl"
os = "linux"

    [[Leptonica.download]]
    sha256 = "bad4ccb198433d4c92ba994fc6674c3887b36775bd9d8688f84e15f957535c74"
    url = "https://github.com/JuliaBinaryWrappers/Leptonica_jll.jl/releases/download/Leptonica-v1.79.0+1/Leptonica.v1.79.0.x86_64-linux-musl.tar.gz"
